# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Azure Credentials

stages:
- stage: Init
  jobs:
  - job: InitTerraform
    steps:
    - script: |
        terraform init \
          -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP_NAME" \
          -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME" \
          -backend-config="container_name=$BACKEND_CONTAINER_NAME" \
          -backend-config="key=$BACKEND_KEY" \
          -backend-config="use_azuread_auth=true"
      workingDirectory: hub
      displayName: Terraform Init
      env:
        BACKEND_RESOURCE_GROUP_NAME: ${BACKEND_RESOURCE_GROUP_NAME}
        BACKEND_STORAGE_ACCOUNT_NAME: ${BACKEND_STORAGE_ACCOUNT_NAME}
        BACKEND_CONTAINER_NAME: ${BACKEND_CONTAINER_NAME}
        BACKEND_KEY: ${BACKEND_KEY}
        BACKEND_ACCESS_KEY: ${BACKEND_ACCESS_KEY}
        ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}
        ARM_TENANT_ID: ${ARM_TENANT_ID}
    - script: |
        terraform plan -out tfplan
      workingDirectory: hub
    - script: |
        terraform apply -auto-approve tfplan
      workingDirectory: hub