# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- rk-infra-test

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- - task: PackerBuild@1
  inputs:
    templateType: 'builtin'
    isManagedImage: true
    baseImageSource: 'default'
    baseImage: 'MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows': |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    terraform plan -out tfplan
    terraform apply tfplan